# Stable features
max_width = 100
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
fn_params_layout = "Tall"
match_block_trailing_comma = true
merge_derives = true
use_try_shorthand = true
use_field_init_shorthand = true
force_explicit_abi = true

# Nightly features (needs nightly rustfmt)
# format_code_in_doc_comments = true
# format_macro_bodies = true
# format_macro_matchers = true
# format_strings = true
# imports_granularity = "Module"
# wrap_comments = true