name: Security audit

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - "**/*.rs"

jobs:
  audit:
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Set up linker configuration
        run: |
          echo "RUSTFLAGS='-C link-dead-code -C debuginfo=2 -C link-arg=-no-pie'" >> $GITHUB_ENV

      - name: Cache cargo-audit
        uses: actions/cache@v3
        with:
          path: ~/.cargo/bin/cargo-audit
          key: ${{ runner.os }}-cargo-audit

      - name: Install cargo-audit
        if: steps.cache-cargo-audit.outputs.cache-hit != 'true'
        run: cargo install cargo-audit

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run security audit
        run: cargo audit

      - name: Run coverage
        run: |
          cargo tarpaulin --avoid-cfg-tarpaulin --out Xml --out Html --out Json --out Lcov
