name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Create Release
        id: create_release
        if: github.actor != 'nektos/act'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
  
  build-release:
    name: Build Release
    needs: create-release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin, aarch64-apple-darwin
          components: clippy
      
      - name: Build for x86_64
        run: cargo build --release --target x86_64-apple-darwin
      
      - name: Build for arm64
        run: cargo build --release --target aarch64-apple-darwin
      
      - name: Create Universal Binary
        run: |
          lipo -create \
            ./target/x86_64-apple-darwin/release/git-rebrand \
            ./target/aarch64-apple-darwin/release/git-rebrand \
            -output git-rebrand-universal
      
      - name: Upload Universal Binary
        if: github.actor != 'nektos/act'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./git-rebrand-universal
          asset_name: git-rebrand-darwin-universal
          asset_content_type: application/octet-stream
