name: Release

permissions:
  contents: write
  pull-requests: write
  issues: write

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  version:
    name: Update Version
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.bump_version.outputs.new_version }}
      changelog: ${{ steps.changelog.outputs.changelog }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ github.token }}

      - name: Get current version
        id: current_version
        run: |
          VERSION=$(grep "^version" Cargo.toml | cut -d '"' -f 2)
          echo "current_version=$VERSION" >> $GITHUB_OUTPUT

      - name: Bump version
        id: bump_version
        run: |
          current=${{ steps.current_version.outputs.current_version }}
          bump_type="${{ github.event.inputs.version_type }}"
          
          IFS='.' read -r major minor patch <<< "$current"
          
          case $bump_type in
            "major")
              new_version="$((major + 1)).0.0"
              ;;
            "minor")
              new_version="${major}.$((minor + 1)).0"
              ;;
            "patch")
              new_version="${major}.${minor}.$((patch + 1))"
              ;;
          esac
          
          echo "new_version=$new_version" >> $GITHUB_OUTPUT
          
          # Update Cargo.toml
          sed -i "s/^version = \".*\"/version = \"$new_version\"/" Cargo.toml

      - name: Generate changelog
        id: changelog
        run: |
          CHANGELOG=$(git log $(git describe --tags --abbrev=0 2>/dev/null || echo HEAD)..HEAD --pretty=format:"- %s (%h)" || git log HEAD~10..HEAD --pretty=format:"- %s (%h)")
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Commit and tag version bump
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add Cargo.toml
          git commit -m "chore: bump version to ${{ steps.bump_version.outputs.new_version }}"
          git tag -a "v${{ steps.bump_version.outputs.new_version }}" -m "Release v${{ steps.bump_version.outputs.new_version }}"
          git push
          git push --tags

  build-release:
    needs: version
    name: macOS Release Build
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-14
            target: aarch64-apple-darwin
    runs-on: ${{ matrix.os }}
    env:
      CARGO_TERM_COLOR: always
      RUST_BACKTRACE: 1
      RUSTC_WRAPPER: ""
    steps:
      - uses: actions/checkout@v4
        with:
          ref: v${{ needs.version.outputs.new_version }}

      - name: Install OpenSSL
        run: |
          brew install openssl@3 pkg-config
          # Set environment variables for both native and cross-compilation
          echo "OPENSSL_DIR=$(brew --prefix openssl@3)" >> $GITHUB_ENV
          echo "OPENSSL_ROOT_DIR=$(brew --prefix openssl@3)" >> $GITHUB_ENV
          echo "OPENSSL_LIB_DIR=$(brew --prefix openssl@3)/lib" >> $GITHUB_ENV
          echo "OPENSSL_INCLUDE_DIR=$(brew --prefix openssl@3)/include" >> $GITHUB_ENV
          # Add pkg-config paths
          echo "PKG_CONFIG_PATH=$(brew --prefix openssl@3)/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
          # Force static linking
          echo "OPENSSL_STATIC=1" >> $GITHUB_ENV
          # Add linker and compiler flags
          echo "LDFLAGS=-L$(brew --prefix openssl@3)/lib" >> $GITHUB_ENV
          echo "CPPFLAGS=-I$(brew --prefix openssl@3)/include" >> $GITHUB_ENV
          echo "LIBRARY_PATH=$(brew --prefix openssl@3)/lib" >> $GITHUB_ENV
          # For cross compilation
          echo "PKG_CONFIG_ALLOW_CROSS=1" >> $GITHUB_ENV
          echo "PKG_CONFIG_ALL_STATIC=1" >> $GITHUB_ENV

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ matrix.os }}-${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: |
          # Ensure pkg-config can find OpenSSL
          export PKG_CONFIG_PATH="$(brew --prefix openssl@3)/lib/pkgconfig:$PKG_CONFIG_PATH"
          # Force static linking
          export OPENSSL_STATIC=1
          export OPENSSL_LIB_DIR=$(brew --prefix openssl@3)/lib
          export OPENSSL_INCLUDE_DIR=$(brew --prefix openssl@3)/include

          cargo build --verbose --release --target ${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binary-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/git-rebrand

  create-universal-binary:
    needs: [version, build-release]
    runs-on: macos-latest
    steps:
      - name: Download x86_64 binary
        uses: actions/download-artifact@v3
        with:
          name: binary-x86_64-apple-darwin
          path: x86_64

      - name: Download arm64 binary
        uses: actions/download-artifact@v3
        with:
          name: binary-aarch64-apple-darwin
          path: arm64

      - name: Create Universal Binary
        run: |
          chmod +x x86_64/git-rebrand arm64/git-rebrand
          lipo -create \
            x86_64/git-rebrand \
            arm64/git-rebrand \
            -output git-rebrand-universal

      - name: Create Release
        if: github.actor != 'nektos/act'
        uses: softprops/action-gh-release@v1
        with:
          files: git-rebrand-universal
          tag_name: v${{ needs.version.outputs.new_version }}
          name: Release v${{ needs.version.outputs.new_version }}
          body: ${{ needs.version.outputs.changelog }}
          draft: false
          prerelease: false

  notify:
    needs: [version, build-release]
    runs-on: ubuntu-latest
    steps:
      - name: Send notification
        if: github.actor != 'nektos/act'
        uses: actions/github-script@v6
        with:
          script: |
            const changelog = `${{ needs.version.outputs.changelog }}`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number || 1,
              body: `🎉 Released version v${{ needs.version.outputs.new_version }}\n\nChangelog:\n${changelog}`
            });
